import json

with open('tech-daily/freshrss_24h_compact_20260610_200500.json', 'r') as f:
    data = json.load(f)
articles = data['articles']

tech_keywords = [
    'code', 'programming', 'developer', 'API', 'framework', 'library',
    'open source', 'github', 'release', 'version', 'python', 'javascript',
    'typescript', 'rust', 'go', 'java', 'database', 'LLM', 'model', 'GPU',
    'kubernetes', 'docker', 'cloud', 'server', 'backend', 'frontend',
    'spark', 'performance', 'optimization', 'algorithm', 'neural',
    'training', 'inference', 'deploy', 'CI/CD', 'devops', 'architecture',
    'diffusion', 'transformer', 'attention', 'embedding', 'vector',
    'query', 'sql', 'graphql', 'rest', 'grpc', 'websocket', 'cache',
    'redis', 'postgres', 'mongodb', 'kafka', 'nginx', 'terraform',
    'aws', 'gcp', 'azure', 'vercel', 'supabase', 'stripe',
    'openai', 'anthropic', 'claude', 'gpt', 'llama', 'huggingface',
    'pytorch', 'tensorflow', 'jax', 'numpy', 'fastapi', 'flask',
    'django', 'express', 'nextjs', 'react', 'vue', 'tailwind',
    'webpack', 'vite', 'babel', 'eslint', 'jest', 'playwright',
    'github actions', 'prometheus', 'grafana', 'postman', 'prisma',
    'sdk', 'cli', 'ide', 'vscode', 'vim', 'terminal', 'shell',
    'linux', 'wasm', 'webassembly', 'microservice', 'container',
    'serverless', 'infrastructure', 'orchestration', 'workflow',
    'apache', 'hadoop', 'flink', 'airflow', 'dbt',
    'pulsar', 'spring', 'blockchain', 'crypto',
    'encryption', 'security', 'vulnerability', 'CVE', 'authentication',
    'oauth', 'jwt', 'tls', 'ssl', 'https', 'http/3', 'quic',
    'compile', 'build', 'test', 'debug', 'benchmark',
    'memory', 'cpu', 'gpu', 'cuda', 'opencl', 'vulkan',
    'simd', 'parallel', 'concurrent', 'async', 'thread',
    'lock-free', 'atomic', 'cache', 'index', 'shard', 'replica',
    'config', 'yaml', 'json', 'toml', 'protobuf',
    'schema', 'migration', 'integration', 'e2e', 'unit',
    'coverage', 'lint', 'format', 'pattern',
    'refactor', 'scalable', 'reliable', 'available',
    'transaction', 'isolation', 'serializability', 'eventual',
    'consensus', 'raft', 'paxos', 'replication',
    'primary', 'secondary', 'leader', 'follower', 'quorum',
    'distributed', 'system', 'network', 'protocol',
    'packet', 'connection', 'session', 'handshake',
    'routing', 'load balancer', 'CDN', 'edge', 'origin',
    'pipeline', 'batch', 'stream processing',
    'event sourcing', 'cqrs', 'saga', 'outbox',
    'idempotent', 'retry', 'timeout',
    'health check', 'metric', 'log', 'trace', 'observability',
    'monitoring', 'alerting', 'anomaly',
    'Kubernetes', 'k8s', 'helm', 'operator',
    'ingress', 'service mesh', 'istio', 'linkerd',
    'argocd', 'argo cd', 'tekton', 'jenkins',
    'prometheus', 'thanos', 'loki', 'tempo',
    'otel', 'opentelemetry', 'jaeger', 'zipkin',
    'otel collector', 'otel sdk',
    'node_exporter', 'cadvisor',
    'kube-state-metrics', 'metrics-server',
    'cluster-autoscaler', 'karpenter',
    'external-dns', 'cert-manager',
    'copilot', 'github copilot', 'cursor',
    'tabnine', 'codeium', 'cody',
    'devin', 'swe-agent', 'swe-bench',
    'claude code', 'claude cli',
    'sonnet', 'opus', 'haiku',
    'gemini', 'deepseek', 'mistral', 'qwen',
    'grok', 'xai',
    'fine-tune', 'batch', 'inference',
    'embedding', 'completion', 'function calling',
    'dall-e', 'stable diffusion', 'flux',
    'sora', 'runway', 'nerf',
    'gaussian splatting', '3dgs',
    'nvidia', 'nvidia cuda', 'nvidia gpu',
    'nvidia tensorrt', 'nvidia triton',
    'amd', 'amd gpu', 'amd rocm',
    'intel', 'intel oneapi', 'intel openvino',
    'apple silicon', 'apple m4', 'apple metal',
    'arm', 'arm cortex', 'arm neoverse',
    'riscv', 'risc-v',
    'tsmc', 'asml', 'euv', 'chip', 'semiconductor',
    'processor', 'core', 'thread', 'socket',
    'DRAM', 'SRAM', 'HBM', 'GDDR',
    'SSD', 'NVMe', 'flash', 'storage',
    'network', 'ethernet', 'infiniband',
    'roce', 'rdma', 'tcp', 'udp',
    'bandwidth', 'latency', 'throughput',
    'IOPS', 'QPS', 'TPS', 'RPS',
    'P99', 'P95', 'P50', 'percentile',
    'SLA', 'SLO', 'SLI', 'error budget',
    'incident', 'postmortem', 'root cause',
    'chaos engineering', 'fault injection',
    'canary', 'blue-green', 'rolling',
    'feature flag', 'toggle', 'launch darkly',
    'ab test', 'experiment', 'rollout',
    'git', 'merge', 'pull request', 'branch',
    'commit', 'diff', 'patch', 'rebase',
    'monorepo', 'polyrepo', 'repository',
    'package', 'dependency', 'lockfile',
    'semver', 'changelog', 'release note',
    'documentation', 'README', 'API doc',
    'swagger', 'openapi', 'postman',
    'graphql', 'subscription', 'mutation',
    'RESTful', 'HATEOAS', 'hypermedia',
    'rpc', 'gRPC', 'thrift', 'protobuf',
    'message queue', 'pub/sub', 'topic',
    'event bus', 'command bus', 'query bus',
    'saga', 'orchestrator', 'choreography',
    'compensating transaction',
    'materialized view', 'projection',
    'read model', 'write model', 'aggregate',
    'domain event', 'integration event',
    'bounded context', 'ubiquitous language',
    'entity', 'value object', 'service',
    'repository', 'factory', 'specification',
    'unit of work', 'domain service',
    'application service', 'infrastructure',
    'cross-cutting concern', 'aspect',
    'middleware', 'interceptor', 'filter',
    'pipe', 'guard', 'decorator',
    'interceptor', 'aspect-oriented',
    'dependency injection', 'IoC container',
    'service locator', 'factory pattern',
    'singleton', 'prototype', 'builder',
    'adapter', 'bridge', 'composite',
    'decorator', 'facade', 'flyweight',
    'proxy', 'chain of responsibility',
    'command', 'interpreter', 'iterator',
    'mediator', 'memento', 'observer',
    'state', 'strategy', 'template method',
    'visitor', 'null object', 'object pool',
    'MVC', 'MVVM', 'MVP', 'VIPER',
    'clean architecture', 'hexagonal',
    'onion', 'layered', 'ports and adapters',
    'microservices', 'service-oriented',
    'event-driven', 'CQRS', 'event sourcing',
    'domain-driven design', 'DDD',
    'test-driven development', 'TDD',
    'behavior-driven development', 'BDD',
    'acceptance test', 'contract test',
    'integration test', 'e2e test',
    'unit test', 'mock', 'stub', 'spy',
    'fake', 'dummy', 'fixture', 'factory',
    'given-when-then', 'arrange-act-assert',
    'red-green-refactor', 'kent beck',
    'martin fowler', 'uncle bob',
    'clean code', 'solid principles',
    'dry', 'kiss', 'yagni',
    'boy scout rule', 'law of demeter',
    'tell dont ask', 'composition over inheritance',
    'favor composition', 'program to interface',
    'dependency inversion', 'interface segregation',
    'liskov substitution', 'open-closed',
    'single responsibility',
    'separation of concerns',
    'code review', 'pair programming',
    'mob programming', 'trunk-based',
    'feature branch', 'git flow',
    'github flow', 'gitlab flow',
    'conventional commit', 'semantic versioning',
    'semantic release', 'conventional changelog',
    'commitlint', 'husky', 'lint-staged',
    'pre-commit', 'git hooks',
    'code formatter', 'prettier', 'black',
    'rustfmt', 'gofmt', 'clang-format',
    'eslint', 'pylint', 'rubocop',
    'shellcheck', 'hadolint', 'tflint',
    'static analysis', 'SAST', 'DAST',
    'code coverage', 'codecov', 'coveralls',
    'sonarqube', 'code climate', 'codacy',
    'deepsource', 'snyk code', 'semgrep',
    'bandit', 'brakeman', 'gosec',
    'tfsec', 'checkov', 'terrascan',
    'vulnerability scanner', 'CVE',
    'OWASP', 'CWE', 'CVSS', 'EPSS',
    'penetration test', 'red team',
    'blue team', 'purple team',
    'threat model', 'STRIDE', 'DREAD',
    'security champion', 'DevSecOps',
    'shift left', 'secure by design',
    'zero trust', 'defense in depth',
    'principle of least privilege',
    'separation of duties',
    'need to know', 'mandatory access',
    'discretionary access', 'RBAC', 'ABAC',
    'policy engine', 'OPA', 'rego',
    'cedar', 'zanzibar',
    'OAuth2', 'OpenID Connect', 'SAML',
    'SSO', 'MFA', '2FA', 'TOTP',
    'WebAuthn', 'FIDO2', 'passkey',
    'biometric', 'certificate',
    'PKI', 'CA', 'TLS', 'mTLS',
    'certificate pinning', 'HPKP',
    'certificate transparency',
    'DANE', 'DNSSEC', 'DoH', 'DoT',
    'IPv6', 'DNS', 'DHCP', 'NAT',
    'VPN', 'proxy', 'reverse proxy',
    'load balancer', 'WAF', 'DDoS',
    'rate limiting', 'throttling',
    'circuit breaker', 'bulkhead',
    'retry', 'timeout', 'hedge',
    'backoff', 'jitter', 'exponential',
    'dead letter queue', 'poison pill',
    'competing consumer', 'saga',
    'outbox pattern', 'inbox pattern',
    'change data capture', 'CDC',
    'debezium', 'maxwell', 'canal',
    'data replication', 'data sync',
    'data migration', 'ETL', 'ELT',
    'data pipeline', 'data warehouse',
    'data lake', 'data lakehouse',
    'data mesh', 'data fabric',
    'data catalog', 'data lineage',
    'data quality', 'data governance',
    'data privacy', 'anonymization',
    'pseudonymization', 'tokenization',
    'masking', 'k-anonymity', 'l-diversity',
    't-closeness', 'differential privacy',
    'federated learning', 'swarm learning',
    'homomorphic encryption',
    'secure multi-party computation',
    'trusted execution environment',
    'TEE', 'SGX', 'SEV', 'TrustZone',
    'confidential computing',
    'memory safety', 'type safety',
    'null safety', 'borrow checker',
    'ownership', 'lifetime', 'lifetime',
    'RAII', 'smart pointer',
    'reference counting', 'ARC',
    'garbage collection', 'GC',
    'mark and sweep', 'generational',
    'incremental', 'concurrent',
    'parallel', 'compacting', 'copying',
    'tri-color', 'write barrier',
    'read barrier', 'card marking',
    'remembered set', 'satb',
    'g1', 'zgc', 'shenandoah',
    'cms', 'parallel old', 'serial',
    'epsilon', 'zing', 'azul',
    'c4', 'pauseless', 'low latency',
    'real-time', 'soft real-time',
    'hard real-time', 'deterministic',
    'WCET', 'schedulability',
    'rate monotonic', 'earliest deadline',
    'least laxity', 'edf', 'rms',
    'priority inversion', 'priority inheritance',
    'priority ceiling', 'deferred server',
    'sporadic server', 'constant bandwidth',
    'aperiodic', 'sporadic', 'periodic',
    'task', 'job', 'thread', 'process',
    'fiber', 'coroutine', 'goroutine',
    'green thread', 'user thread',
    'kernel thread', 'lightweight process',
    'pthread', 'win32 thread',
    'thread pool', 'worker pool',
    'executor', 'scheduler', 'dispatcher',
    'reactor', 'proactor', 'completion port',
    'epoll', 'kqueue', 'io_uring',
    'io completion port', 'overlapped',
    'aio', 'libaio', 'io_submit',
    'eventfd', 'signalfd', 'timerfd',
    'pipe', 'fifo', 'socketpair',
    'unix socket', 'domain socket',
    'named pipe', 'message queue',
    'shared memory', 'memory mapping',
    'mmap', 'mprotect', 'madvise',
    'posix shared memory', 'sysv shm',
    'semaphore', 'mutex', 'condition variable',
    'barrier', 'rwlock', 'spinlock',
    'futex', 'event', 'critical section',
    'monitor', 'synchronized', 'lock',
    'deadlock', 'livelock', 'starvation',
    'race condition', 'data race',
    'memory ordering', 'acquire', 'release',
    'seq_cst', 'relaxed', 'consume',
    'fence', 'barrier', 'compiler barrier',
    'cache coherence', 'cache line',
    'false sharing', 'padding', 'align',
    'prefetch', 'branch prediction',
    'speculative execution', 'out-of-order',
    'superscalar', 'pipelining',
    'instruction level parallelism',
    'data level parallelism',
    'task level parallelism',
    'SIMD', 'SSE', 'AVX', 'AVX2', 'AVX-512',
    'NEON', 'SVE', 'SVE2', 'RISC-V V',
    'OpenMP', 'MPI', 'oneAPI', 'SYCL',
    'HIP', 'ROCm', 'CUDA', 'OpenCL',
    'Vulkan', 'Metal', 'DirectX',
    'OpenGL', 'WebGL', 'WebGPU',
    'shader', 'compute shader',
    'vertex shader', 'fragment shader',
    'geometry shader', 'tessellation',
    'ray tracing shader', 'mesh shader',
    'task shader', 'amplification',
    'DLSS', 'FSR', 'XeSS', 'TSR',
    'ray tracing', 'path tracing',
    'radiosity', 'photon mapping',
    'global illumination', 'ambient occlusion',
    'screen space', 'ray marched',
    'signed distance field', 'SDF',
    'voxel', 'octree', 'BVH', 'k-d tree',
    'spatial hash', 'uniform grid',
    'broad phase', 'narrow phase',
    'collision detection', 'physics engine',
    'rigid body', 'soft body', 'cloth',
    'fluid', 'particle system',
    'constraint solver', 'impulse',
    'velocity', 'position', 'verlet',
    'euler integration', 'runge-kutta',
    'symplectic', 'leapfrog',
    'game engine', 'unreal engine',
    'unity', 'godot', 'bevy',
    'rendering engine', 'browser engine',
    'layout engine', 'javascript engine',
    'V8', 'SpiderMonkey', 'JavaScriptCore',
    'Chakra', 'Nitro', 'Hermes',
    'QuickJS', 'Deno', 'Bun', 'Node.js',
    'npm', 'pnpm', 'yarn', 'bun',
    'package manager', 'lockfile',
    'node_modules', 'monorepo',
    'workspace', 'turborepo', 'nx',
    'lerna', 'rush', 'bazel',
    'webpack', 'rollup', 'vite',
    'esbuild', 'parcel', 'turbopack',
    'rspack', 'farm', 'swc',
    'babel', 'typescript', 'tsc',
    'type checker', 'type inference',
    'generic', 'interface', 'union',
    'intersection', 'conditional type',
    'mapped type', 'template literal',
    'infer', 'extends', 'satisfies',
    'asserts', 'is', 'in', 'as',
    'const assertion', 'enum', 'namespace',
    'module', 'ambient', 'declaration',
    'triple-slash', 'reference',
    'tsconfig', 'compiler option',
    'strict', 'noImplicitAny',
    'strictNullChecks', 'exactOptionalPropertyTypes',
    'noUncheckedIndexedAccess',
    'isolatedModules', 'esModuleInterop',
    'skipLibCheck', 'declarationMap',
    'sourceMap', 'inlineSourceMap',
    'outDir', 'rootDir', 'baseUrl',
    'paths', 'types', 'typeRoots',
    'lib', 'target', 'module',
    'moduleResolution', 'jsx',
    'jsxFactory', 'jsxFragmentFactory',
    'jsxImportSource', 'reactNamespace',
    'noEmit', 'emitDeclarationOnly',
    'declaration', 'composite',
    'incremental', 'tsBuildInfoFile',
    'resolveJsonModule', 'allowJs',
    'checkJs', 'maxNodeModuleJsDepth',
    'react', 'react-dom', 'next.js',
    'vue', 'nuxt', 'svelte', 'sveltekit',
    'angular', 'solid', 'qwik',
    'preact', 'lit', 'htmx',
    'alpine', 'stimulus', 'hotwire',
    'turbo', 'stimulus reflex',
    'cable ready', 'anycable',
    'actioncable', 'websocket',
    'server-sent event', 'SSE',
    'long polling', 'polling',
    'graphql subscription',
    'real-time', 'live query',
    'reactive', 'signal', 'observable',
    'computed', 'effect', 'memo',
    'derive', 'store', 'atom',
    'jotai', 'zustand', 'valtio',
    'recoil', 'redux', 'mobx',
    'zustand', 'jotai', 'xstate',
    'immer', 'valtio', 'proxy',
    'useSyncExternalStore',
    'context', 'provider', 'consumer',
    'useReducer', 'useState', 'useEffect',
    'useMemo', 'useCallback', 'useRef',
    'useLayoutEffect', 'useImperativeHandle',
    'useDebugValue', 'useId', 'useDeferredValue',
    'useTransition', 'useActionState',
    'useOptimistic', 'useFormStatus',
    'server action', 'server function',
    'server component', 'client component',
    'use client', 'use server',
    'streaming', 'suspense',
    'error boundary', 'loading state',
    'not found', 'parallel route',
    'intercepting route', 'route group',
    'dynamic route', 'catch-all',
    'optional catch-all',
    'generateStaticParams',
    'revalidatePath', 'revalidateTag',
    'unstable_cache', 'unstable_revalidate',
    'draftMode', 'previewData',
    'middleware', 'matcher', 'config',
    'edge runtime', 'nodejs runtime',
    'wasm edge', 'edge function',
    'ISR', 'SSG', 'SSR', 'CSR',
    'hydration', 'rehydration',
    'selective hydration',
    'progressive enhancement',
    'graceful degradation',
    'responsive', 'adaptive',
    'mobile-first', 'desktop-first',
    'container query', 'CSS grid',
    'flexbox', 'subgrid', ' masonry',
    'clamp', 'min', 'max', 'calc',
    'custom property', 'CSS variable',
    'design token', 'theme',
    'dark mode', 'light mode',
    'system preference', 'color scheme',
    'prefers-color-scheme',
    'prefers-reduced-motion',
    'prefers-reduced-transparency',
    'prefers-contrast', 'forced-colors',
    'accessibility', 'a11y', 'ARIA',
    'screen reader', 'keyboard navigation',
    'focus management', 'focus trap',
    'skip link', 'landmark',
    'semantic HTML', 'heading hierarchy',
    'alt text', 'caption', 'transcript',
    'WCAG', 'Section 508', 'EN 301 549',
    'audit', 'lighthouse', 'axe',
    'pa11y', 'eslint-plugin-jsx-a11y',
    'testing library', 'jest', 'vitest',
    'cypress', 'playwright', 'selenium',
    'webdriver', 'puppeteer',
    'msw', 'nock', 'mirage',
    'storybook', 'chromatic',
    'percy', 'applitools',
    'backstopjs', 'loki',
    'regression testing',
    'visual testing', 'snapshot',
    'component testing', 'unit testing',
    'integration testing', 'e2e testing',
    'contract testing', 'pact',
    'consumer-driven contract',
    'API testing', 'load testing',
    'stress testing', 'soak testing',
    'spike testing', 'chaos testing',
    'performance testing', 'benchmark',
    'profiling', 'flame graph',
    'cpu profile', 'memory profile',
    'heap snapshot', 'allocation profile',
    'timeline', 'tracing', 'devtools',
    'chrome devtools', 'firefox devtools',
    'safari devtools', 'edge devtools',
    'react devtools', 'redux devtools',
    'vue devtools', 'angular devtools',
    'svelte devtools', 'solid devtools',
    'network panel', 'performance panel',
    'memory panel', 'application panel',
    'security panel', 'lighthouse panel',
    'console', 'debugger', 'breakpoint',
    'conditional breakpoint', 'logpoint',
    'watch', 'call stack', 'scope',
    'source map', 'pretty print',
    'blackbox', 'ignore list',
    'workspace', 'local override',
    'device emulation', 'throttling',
    'coverage', 'rendering',
    'animations', 'layers',
    'recorder', 'issues', 'insights',
]

exclude_keywords = [
    'ipo', 'stock price', 'market cap', 'valuation', 'funding round',
    'venture capital', 'share price', 'earnings',
    'quarterly earnings', 'fiscal year',
    'acquisition', 'merger', 'buyout',
    ' layoff', 'fired', 'hiring freeze',
    'executive appointment', 'new ceo',
    'antitrust', 'lawsuit', 'patent suit',
    'trade war', 'sanction', 'tariff',
    'political', 'election', 'campaign',
    'climate change', 'carbon',
]

dev_articles = []
for a in articles:
    text = (a.get('title','') + ' ' + a.get('summary','') + ' ' + a.get('feed_title','')).lower()
    score = 0
    for kw in tech_keywords:
        if kw.lower() in text:
            score += 1
    exclude_score = 0
    for ek in exclude_keywords:
        if ek.lower() in text:
            exclude_score += 1
    if score >= 2 and exclude_score < 2:
        dev_articles.append((score, a))

dev_articles.sort(key=lambda x: -x[0])
print(f'Found {len(dev_articles)} developer-related articles')
for score, a in dev_articles[:60]:
    title = a['title'][:110]
    print(f'[{score}] [{a["feed_title"]}] {title}')
